-- Baseline schema migration
-- Generated from live database state on 2026-07-07
-- Purpose: bring supabase/migrations/ in sync with the actual production schema,
-- since prior table/policy changes were made via the dashboard rather than tracked migrations.
--
-- This file is a snapshot, not a step-by-step history. It should be the FIRST
-- migration in the repo. Do not re-run it against the live project (tables already exist) —
-- it's for rebuilding the schema elsewhere (new environment, branch, disaster recovery).

-- ============================================================
-- FUNCTIONS
-- ============================================================

CREATE OR REPLACE FUNCTION public.auth_tenant_id()
 RETURNS text
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  SELECT id::text FROM tenants
  WHERE id::text = (auth.jwt() -> 'user_metadata' ->> 'tenant')
  LIMIT 1
$function$;

-- ============================================================
-- TABLES
-- ============================================================

CREATE TABLE public.tenants (
  id text PRIMARY KEY,
  name text UNIQUE NOT NULL,
  logo_url text,
  primary_color text DEFAULT '#1A365D',
  accent_color text DEFAULT '#E03E15',
  contact_email text,
  contact_phone text,
  footer_text text,
  signoff_name text,
  signoff_role text DEFAULT 'Project Manager',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.assessors (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id text NOT NULL REFERENCES public.tenants(id),
  full_name text NOT NULL,
  role text,
  email text,
  phone text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.clients (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id text NOT NULL REFERENCES public.tenants(id),
  client_name text NOT NULL,
  contact_person text,
  contact_number text,
  contact_email text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  deleted_at timestamptz
);

CREATE TABLE public.qualifications (
  id text PRIMARY KEY,
  tenant_id text NOT NULL REFERENCES public.tenants(id),
  saqa_id text NOT NULL,
  qualification_code text,
  name text NOT NULL,
  total_credits integer,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.programmes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id text NOT NULL REFERENCES public.tenants(id),
  client_id bigint REFERENCES public.clients(id),
  qualification_id text REFERENCES public.qualifications(id),
  facilitator_id bigint REFERENCES public.assessors(id),
  programme_name text NOT NULL,
  saqa_id text,
  qualification_code text,
  group_name text,
  group_size integer,
  module_1_dates text,
  module_2_dates text,
  module_3_dates text,
  module_4_dates text,
  report_due_date date,
  start_date date,
  end_date date,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  deleted_at timestamptz
);

CREATE TABLE public.learners (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id text NOT NULL REFERENCES public.tenants(id),
  first_name text NOT NULL,
  last_name text NOT NULL,
  id_number text,
  email text,
  phone text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.enrolments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id text NOT NULL REFERENCES public.tenants(id),
  learner_id bigint NOT NULL REFERENCES public.learners(id),
  programme_id bigint NOT NULL REFERENCES public.programmes(id),
  status text DEFAULT 'active',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.attendance (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id text NOT NULL REFERENCES public.tenants(id),
  programme_id bigint NOT NULL REFERENCES public.programmes(id),
  learner_id bigint NOT NULL REFERENCES public.learners(id),
  session_date date NOT NULL,
  status text DEFAULT 'P',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.eisa (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id text NOT NULL REFERENCES public.tenants(id),
  programme_id bigint NOT NULL REFERENCES public.programmes(id),
  learner_id bigint NOT NULL REFERENCES public.learners(id),
  module_number integer NOT NULL DEFAULT 1,
  km_result text,
  pm_result text,
  wm_result text,
  exam_v1_result text,
  exam_v1_pct text,
  exam_v2_result text,
  exam_v2_pct text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.unit_standards (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id text NOT NULL REFERENCES public.tenants(id),
  saqa_id text NOT NULL,
  qualification_id text REFERENCES public.qualifications(id),
  us_id text NOT NULL,
  us_title text,
  us_level integer,
  us_credits integer,
  module_number integer,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.program_modules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id text NOT NULL REFERENCES public.tenants(id),
  programme_id bigint NOT NULL REFERENCES public.programmes(id),
  module_number integer NOT NULL,
  title text,
  dates text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.drafts (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  tenant_id text NOT NULL REFERENCES public.tenants(id),
  programme_id bigint NOT NULL,
  month text NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}',
  updated_at timestamptz NOT NULL DEFAULT now(),
  client_name text,
  programme_name text,
  saved_at timestamptz DEFAULT now()
);

CREATE TABLE public.reports (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  tenant_id text NOT NULL REFERENCES public.tenants(id),
  client_id bigint,
  programme_id bigint,
  saqa_id text,
  month text,
  learner_count integer DEFAULT 0,
  printed_at timestamptz NOT NULL DEFAULT now(),
  status text DEFAULT 'pending',
  reviewer_note text,
  reviewed_by text,
  reviewed_at timestamptz,
  client_name_snapshot text,
  programme_name_snapshot text,
  sent_at timestamptz,
  sent_by text,
  archived_at timestamptz,
  archived_by text
);

CREATE TABLE public.learner_comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id text NOT NULL REFERENCES public.tenants(id),
  learner_id bigint NOT NULL REFERENCES public.learners(id),
  programme_id bigint NOT NULL REFERENCES public.programmes(id),
  month text NOT NULL,
  comment text,
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.notifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id text NOT NULL REFERENCES public.tenants(id),
  report_ref text,
  decision text,
  message text,
  created_at timestamptz DEFAULT now(),
  read boolean NOT NULL DEFAULT false,
  type text
);

CREATE TABLE public.programme_notes (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  tenant_id text NOT NULL REFERENCES public.tenants(id),
  programme_id bigint NOT NULL REFERENCES public.programmes(id),
  month text,
  type text NOT NULL CHECK (type = ANY (ARRAY['monitoring'::text, 'recommendation'::text])),
  content text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action text NOT NULL,
  table_name text NOT NULL,
  record_id text NOT NULL,
  user_name text,
  user_role text,
  changes jsonb,
  created_at timestamptz DEFAULT now(),
  tenant_id text REFERENCES public.tenants(id)
);

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

ALTER TABLE public.tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assessors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.qualifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.programmes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.learners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.enrolments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.eisa ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.unit_standards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.program_modules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.drafts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.learner_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.programme_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;

-- tenants: public read (needed to resolve tenant branding before login)
CREATE POLICY anon_read ON public.tenants FOR SELECT TO anon, authenticated USING (true);

-- standard tenant-scoped access, applied consistently across tables
CREATE POLICY tenant_all ON public.assessors FOR ALL TO authenticated
  USING (tenant_id = auth_tenant_id()) WITH CHECK (tenant_id = auth_tenant_id());

CREATE POLICY tenant_all ON public.clients FOR ALL TO authenticated
  USING (tenant_id = auth_tenant_id()) WITH CHECK (tenant_id = auth_tenant_id());

CREATE POLICY tenant_all ON public.qualifications FOR ALL TO public
  USING (tenant_id = auth_tenant_id()) WITH CHECK (tenant_id = auth_tenant_id());

CREATE POLICY tenant_all ON public.programmes FOR ALL TO authenticated
  USING (tenant_id = auth_tenant_id()) WITH CHECK (tenant_id = auth_tenant_id());

CREATE POLICY tenant_all ON public.learners FOR ALL TO authenticated
  USING (tenant_id = auth_tenant_id()) WITH CHECK (tenant_id = auth_tenant_id());

CREATE POLICY tenant_all ON public.enrolments FOR ALL TO authenticated
  USING (tenant_id = auth_tenant_id()) WITH CHECK (tenant_id = auth_tenant_id());

CREATE POLICY tenant_all ON public.attendance FOR ALL TO authenticated
  USING (tenant_id = auth_tenant_id()) WITH CHECK (tenant_id = auth_tenant_id());

-- eisa: split by command (matches live config) rather than a single ALL policy
CREATE POLICY eisa_tenant_select ON public.eisa FOR SELECT TO public
  USING (tenant_id = auth_tenant_id());
CREATE POLICY eisa_tenant_insert ON public.eisa FOR INSERT TO public
  WITH CHECK (tenant_id = auth_tenant_id());
CREATE POLICY eisa_tenant_update ON public.eisa FOR UPDATE TO public
  USING (tenant_id = auth_tenant_id()) WITH CHECK (tenant_id = auth_tenant_id());
CREATE POLICY eisa_tenant_delete ON public.eisa FOR DELETE TO public
  USING (tenant_id = auth_tenant_id());
CREATE POLICY tenant_all ON public.eisa FOR ALL TO authenticated
  USING (tenant_id = auth_tenant_id()) WITH CHECK (tenant_id = auth_tenant_id());

CREATE POLICY tenant_all ON public.unit_standards FOR ALL TO authenticated
  USING (tenant_id = auth_tenant_id()) WITH CHECK (tenant_id = auth_tenant_id());

CREATE POLICY tenant_all ON public.program_modules FOR ALL TO public
  USING (tenant_id = auth_tenant_id()) WITH CHECK (tenant_id = auth_tenant_id());

-- drafts: single correct tenant-scoped policy.
-- NOTE: a second policy ("tenant isolation") previously existed here with an
-- "OR true" clause that bypassed tenant isolation entirely for all roles.
-- It was removed on 2026-07-07 as a security fix; do not reintroduce it.
CREATE POLICY tenant_all ON public.drafts FOR ALL TO authenticated
  USING (tenant_id = auth_tenant_id()) WITH CHECK (tenant_id = auth_tenant_id());

-- reports: split by command (matches live config) plus a catch-all for authenticated
CREATE POLICY reports_tenant_select ON public.reports FOR SELECT TO public
  USING (tenant_id = auth_tenant_id());
CREATE POLICY reports_tenant_insert ON public.reports FOR INSERT TO public
  WITH CHECK (tenant_id = auth_tenant_id());
CREATE POLICY reports_tenant_update ON public.reports FOR UPDATE TO public
  USING (tenant_id = auth_tenant_id()) WITH CHECK (tenant_id = auth_tenant_id());
CREATE POLICY reports_tenant_delete ON public.reports FOR DELETE TO public
  USING (tenant_id = auth_tenant_id());
CREATE POLICY tenant_all ON public.reports FOR ALL TO authenticated
  USING (tenant_id = auth_tenant_id()) WITH CHECK (tenant_id = auth_tenant_id());

CREATE POLICY tenant_all ON public.learner_comments FOR ALL TO public
  USING (tenant_id = auth_tenant_id()) WITH CHECK (tenant_id = auth_tenant_id());

CREATE POLICY tenant_all ON public.notifications FOR ALL TO authenticated
  USING (tenant_id = auth_tenant_id()) WITH CHECK (tenant_id = auth_tenant_id());

CREATE POLICY tenant_all ON public.programme_notes FOR ALL TO public
  USING (tenant_id = auth_tenant_id()) WITH CHECK (tenant_id = auth_tenant_id());

CREATE POLICY audit_log_tenant_all ON public.audit_log FOR ALL TO authenticated
  USING (tenant_id = auth_tenant_id()) WITH CHECK (tenant_id = auth_tenant_id());
